/**
 * Resolve a Lucide icon name string to a React component.
 *
 * Dynamic panels declare their icon as a string (e.g. "activity", "cpu").
 * This maps those strings to the corresponding lucide-react component.
 *
 * ponytail: curated map instead of `import * as LucideIcons` — the namespace
 * import defeated tree-shaking and kept every lucide icon (~860KB minified)
 * in the main bundle, which the mobile WebView can't afford. Unknown names
 * fall back to Square; add entries here as services need them.
 */
import React from "react";
import {
    Activity,
    AlarmClock,
    AlertTriangle,
    Anchor,
    Archive,
    Atom,
    Award,
    Banknote,
    BatteryCharging,
    Bell,
    BellOff,
    BellRing,
    BookOpen,
    Bot,
    Box,
    Braces,
    Brain,
    Briefcase,
    Bug,
    Building2,
    Cake,
    Calculator,
    Calendar,
    CalendarClock,
    Camera,
    Car,
    ChartBar,
    ChartLine,
    ChartPie,
    Check,
    ChefHat,
    Circle,
    CircleAlert,
    CircleCheck,
    CircleDollarSign,
    CircleHelp,
    CircleStop,
    CircleX,
    Clipboard,
    ClipboardList,
    Clock,
    Cloud,
    Code,
    Coffee,
    Compass,
    Copy,
    Cpu,
    CreditCard,
    Crown,
    Database,
    Dices,
    Diff,
    DollarSign,
    Download,
    Droplet,
    ExternalLink,
    Eye,
    EyeOff,
    Factory,
    File,
    FileCode,
    FileJson,
    FileText,
    Film,
    Filter,
    Fingerprint,
    Flag,
    Flame,
    FlaskConical,
    Folder,
    FolderGit2,
    FolderOpen,
    Gamepad2,
    Gauge,
    Gem,
    Gift,
    GitBranch,
    GitCommitHorizontal,
    Github,
    GitMerge,
    GitPullRequest,
    Globe,
    GraduationCap,
    Hammer,
    Handshake,
    HardDrive,
    Heart,
    HeartPulse,
    History,
    Home,
    Hourglass,
    House,
    Image,
    Inbox,
    Info,
    Key,
    Landmark,
    Languages,
    Layers,
    LayoutDashboard,
    LayoutGrid,
    Leaf,
    Library,
    Lightbulb,
    Link,
    List,
    ListChecks,
    ListTodo,
    Lock,
    LogIn,
    LogOut,
    Mail,
    Map,
    MapPin,
    Megaphone,
    Menu,
    MessageCircle,
    MessageSquare,
    Microscope,
    Mic,
    Monitor,
    Moon,
    MousePointerClick,
    Music,
    Network,
    Newspaper,
    NotebookPen,
    Package,
    Paintbrush,
    Palette,
    Paperclip,
    PartyPopper,
    Pause,
    Pencil,
    Phone,
    Pill,
    Pin,
    Pizza,
    Puzzle,
    Plane,
    Play,
    Plug,
    Power,
    Radio,
    Receipt,
    RefreshCw,
    Repeat,
    Rocket,
    Router,
    Rss,
    Ruler,
    Scale,
    Scissors,
    ScrollText,
    Search,
    Send,
    Server,
    Settings,
    Shield,
    ShieldAlert,
    ShieldCheck,
    Ship,
    ShoppingCart,
    Shuffle,
    Signal,
    SkipForward,
    Smartphone,
    Smile,
    Sparkles,
    Square,
    SquareKanban,
    Star,
    Stethoscope,
    StickyNote,
    Store,
    Sun,
    Table,
    Tag,
    Target,
    Telescope,
    Terminal,
    TerminalSquare,
    Thermometer,
    ThumbsDown,
    ThumbsUp,
    Timer,
    Train,
    Trash2,
    TrendingDown,
    TrendingUp,
    Trophy,
    Truck,
    Unlock,
    Upload,
    User,
    UserCheck,
    UserPlus,
    Users,
    Utensils,
    Video,
    Volume2,
    Wallet,
    Webhook,
    Wifi,
    Workflow,
    Wrench,
    Zap,
    type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
    "activity": Activity,
    "alarm-clock": AlarmClock,
    "alert-circle": CircleAlert,
    "alert-triangle": AlertTriangle,
    "anchor": Anchor,
    "archive": Archive,
    "atom": Atom,
    "award": Award,
    "banknote": Banknote,
    "bar-chart": ChartBar,
    "battery-charging": BatteryCharging,
    "bell": Bell,
    "bell-off": BellOff,
    "bell-ring": BellRing,
    "book-open": BookOpen,
    "bot": Bot,
    "box": Box,
    "braces": Braces,
    "brain": Brain,
    "briefcase": Briefcase,
    "bug": Bug,
    "building-2": Building2,
    "cake": Cake,
    "calculator": Calculator,
    "calendar": Calendar,
    "calendar-clock": CalendarClock,
    "camera": Camera,
    "car": Car,
    "chart-bar": ChartBar,
    "chart-line": ChartLine,
    "chart-pie": ChartPie,
    "check": Check,
    "check-circle": CircleCheck,
    "chef-hat": ChefHat,
    "circle": Circle,
    "circle-alert": CircleAlert,
    "circle-check": CircleCheck,
    "circle-dollar-sign": CircleDollarSign,
    "circle-help": CircleHelp,
    "circle-stop": CircleStop,
    "circle-x": CircleX,
    "clipboard": Clipboard,
    "clipboard-list": ClipboardList,
    "clock": Clock,
    "cloud": Cloud,
    "code": Code,
    "coffee": Coffee,
    "compass": Compass,
    "copy": Copy,
    "cpu": Cpu,
    "credit-card": CreditCard,
    "crown": Crown,
    "database": Database,
    "dices": Dices,
    "diff": Diff,
    "dollar-sign": DollarSign,
    "download": Download,
    "droplet": Droplet,
    "external-link": ExternalLink,
    "eye": Eye,
    "eye-off": EyeOff,
    "factory": Factory,
    "file": File,
    "file-code": FileCode,
    "file-json": FileJson,
    "file-text": FileText,
    "film": Film,
    "filter": Filter,
    "fingerprint": Fingerprint,
    "flag": Flag,
    "flame": Flame,
    "flask-conical": FlaskConical,
    "folder": Folder,
    "folder-git-2": FolderGit2,
    "folder-open": FolderOpen,
    "gamepad-2": Gamepad2,
    "gauge": Gauge,
    "gem": Gem,
    "gift": Gift,
    "git-branch": GitBranch,
    "git-commit-horizontal": GitCommitHorizontal,
    "git-merge": GitMerge,
    "git-pull-request": GitPullRequest,
    "github": Github,
    "globe": Globe,
    "graduation-cap": GraduationCap,
    "hammer": Hammer,
    "handshake": Handshake,
    "hard-drive": HardDrive,
    "heart": Heart,
    "heart-pulse": HeartPulse,
    "help-circle": CircleHelp,
    "history": History,
    "home": Home,
    "house": House,
    "hourglass": Hourglass,
    "image": Image,
    "inbox": Inbox,
    "info": Info,
    "kanban-square": SquareKanban,
    "key": Key,
    "landmark": Landmark,
    "languages": Languages,
    "layers": Layers,
    "layout-dashboard": LayoutDashboard,
    "layout-grid": LayoutGrid,
    "leaf": Leaf,
    "library": Library,
    "lightbulb": Lightbulb,
    "line-chart": ChartLine,
    "link": Link,
    "list": List,
    "list-checks": ListChecks,
    "list-todo": ListTodo,
    "lock": Lock,
    "log-in": LogIn,
    "log-out": LogOut,
    "mail": Mail,
    "map": Map,
    "map-pin": MapPin,
    "megaphone": Megaphone,
    "menu": Menu,
    "message-circle": MessageCircle,
    "microscope": Microscope,
    "message-square": MessageSquare,
    "mic": Mic,
    "monitor": Monitor,
    "moon": Moon,
    "mouse-pointer-click": MousePointerClick,
    "music": Music,
    "network": Network,
    "newspaper": Newspaper,
    "notebook-pen": NotebookPen,
    "package": Package,
    "paintbrush": Paintbrush,
    "palette": Palette,
    "paperclip": Paperclip,
    "party-popper": PartyPopper,
    "pause": Pause,
    "pencil": Pencil,
    "phone": Phone,
    "pie-chart": ChartPie,
    "pill": Pill,
    "pin": Pin,
    "pizza": Pizza,
    "puzzle": Puzzle,
    "plane": Plane,
    "play": Play,
    "plug": Plug,
    "power": Power,
    "radio": Radio,
    "receipt": Receipt,
    "refresh-cw": RefreshCw,
    "repeat": Repeat,
    "rocket": Rocket,
    "router": Router,
    "rss": Rss,
    "ruler": Ruler,
    "scale": Scale,
    "scissors": Scissors,
    "scroll-text": ScrollText,
    "search": Search,
    "send": Send,
    "server": Server,
    "settings": Settings,
    "shield": Shield,
    "shield-alert": ShieldAlert,
    "shield-check": ShieldCheck,
    "ship": Ship,
    "shopping-cart": ShoppingCart,
    "shuffle": Shuffle,
    "signal": Signal,
    "skip-forward": SkipForward,
    "smartphone": Smartphone,
    "smile": Smile,
    "sparkles": Sparkles,
    "square": Square,
    "square-kanban": SquareKanban,
    "star": Star,
    "stethoscope": Stethoscope,
    "sticky-note": StickyNote,
    "stop-circle": CircleStop,
    "store": Store,
    "sun": Sun,
    "table": Table,
    "tag": Tag,
    "target": Target,
    "telescope": Telescope,
    "terminal": Terminal,
    "terminal-square": TerminalSquare,
    "thermometer": Thermometer,
    "thumbs-down": ThumbsDown,
    "thumbs-up": ThumbsUp,
    "timer": Timer,
    "train": Train,
    "trash": Trash2,
    "trash-2": Trash2,
    "trending-down": TrendingDown,
    "trending-up": TrendingUp,
    "trophy": Trophy,
    "truck": Truck,
    "unlock": Unlock,
    "upload": Upload,
    "user": User,
    "user-check": UserCheck,
    "user-plus": UserPlus,
    "users": Users,
    "utensils": Utensils,
    "video": Video,
    "volume-2": Volume2,
    "wallet": Wallet,
    "webhook": Webhook,
    "wifi": Wifi,
    "workflow": Workflow,
    "wrench": Wrench,
    "x-circle": CircleX,
    "zap": Zap,
};

/**
 * Get a Lucide icon component by name. Returns Square if not found.
 */
export function getLucideIcon(name: string): LucideIcon {
    return ICONS[name] ?? Square;
}

/**
 * Render a Lucide icon by name string with standard panel icon sizing.
 */
export function DynamicLucideIcon({ name, className = "size-3.5" }: { name: string; className?: string }) {
    const Icon = getLucideIcon(name);
    return <Icon className={className} />;
}
