/**
 * MCP OAuth callback proxy route.
 *
 * When a remote MCP server completes OAuth authorization, it redirects the
 * user's browser to this endpoint. We extract the authorization code and
 * forward it to the runner (via the relay WebSocket) so it can exchange the
 * code for an access token.
 *
 * URL: GET /api/mcp-oauth-callback?code=...&state=...
 *
 * The `state` parameter encodes:
 *   { sessionId: string, nonce: string, oauthState?: string }
 *
 * The nonce prevents replay. The oauthState (if present) is the original
 * OAuth state value generated by the MCP SDK for CSRF protection.
 */

import type { RouteHandler } from "./types.js";
import { getLocalTuiSocket } from "../ws/sio-registry.js";

/** In-memory set of consumed nonces to prevent replay (cleared periodically). */
const consumedNonces = new Set<string>();

// Clean up old nonces every 10 minutes
setInterval(() => consumedNonces.clear(), 10 * 60 * 1000);

export const handleMcpOAuthRoute: RouteHandler = async (req, url) => {
    if (url.pathname !== "/api/mcp-oauth-callback") return undefined;
    if (req.method !== "GET") return undefined;

    const code = url.searchParams.get("code");
    const stateRaw = url.searchParams.get("state");
    const error = url.searchParams.get("error");

    // ── Error from OAuth provider ────────────────────────────────────────
    if (error) {
        const desc = url.searchParams.get("error_description") ?? error;
        return new Response(
            htmlPage("Authentication Failed", `<p>❌ ${escapeHtml(desc)}</p><p>You can close this tab.</p>`),
            { status: 400, headers: { "Content-Type": "text/html" } },
        );
    }

    // ── Parse state ──────────────────────────────────────────────────────
    if (!code || !stateRaw) {
        return new Response(
            htmlPage("Bad Request", "<p>Missing code or state parameter.</p>"),
            { status: 400, headers: { "Content-Type": "text/html" } },
        );
    }

    let state: { sessionId?: string; nonce?: string; oauthState?: string };
    try {
        state = JSON.parse(Buffer.from(stateRaw, "base64url").toString("utf-8"));
    } catch {
        return new Response(
            htmlPage("Bad Request", "<p>Invalid state parameter.</p>"),
            { status: 400, headers: { "Content-Type": "text/html" } },
        );
    }

    const { sessionId, nonce } = state;
    if (!sessionId || !nonce) {
        return new Response(
            htmlPage("Bad Request", "<p>Invalid state: missing sessionId or nonce.</p>"),
            { status: 400, headers: { "Content-Type": "text/html" } },
        );
    }

    // ── Replay protection ────────────────────────────────────────────────
    const nonceKey = `${sessionId}:${nonce}`;
    if (consumedNonces.has(nonceKey)) {
        return new Response(
            htmlPage("Already Used", "<p>This callback has already been processed.</p>"),
            { status: 409, headers: { "Content-Type": "text/html" } },
        );
    }

    // ── Forward to runner ────────────────────────────────────────────────
    const socket = getLocalTuiSocket(sessionId);
    if (!socket) {
        // Don't consume the nonce — the session may reconnect and retry.
        return new Response(
            htmlPage("Session Not Found", "<p>The agent session is no longer connected. Please try again.</p>"),
            { status: 404, headers: { "Content-Type": "text/html" } },
        );
    }

    // Mark nonce consumed only after confirming the session socket exists,
    // so a retry can succeed if the session was temporarily disconnected.
    consumedNonces.add(nonceKey);

    // Emit to the runner's relay socket. The remote extension listens for
    // this event and forwards it to the OAuth provider.
    socket.emit("mcp_oauth_callback" as any, {
        sessionId,
        nonce,
        code,
        oauthState: state.oauthState,
    });

    return new Response(
        htmlPage("Authentication Successful", `
            <p>✅ Authentication successful!</p>
            <p>You can close this tab and return to your session.</p>
            <script>setTimeout(() => window.close(), 2000);</script>
        `),
        { status: 200, headers: { "Content-Type": "text/html" } },
    );
};

// ── HTML helpers ─────────────────────────────────────────────────────────────

function escapeHtml(s: string): string {
    return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function htmlPage(title: string, body: string): string {
    return `<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>${escapeHtml(title)} — PizzaPi</title>
    <style>
        body { font-family: system-ui, sans-serif; max-width: 480px; margin: 80px auto; text-align: center; }
        h2 { margin-bottom: 0.5em; }
        p { color: #555; }
    </style>
</head>
<body>
    <h2>${escapeHtml(title)}</h2>
    ${body}
</body>
</html>`;
}
