/**
 * MCP OAuth callback proxy route.
 *
 * When a remote MCP server completes OAuth authorization, it redirects the
 * user's browser to this endpoint. We extract the authorization code and
 * forward it to the runner (via the relay WebSocket) so it can exchange the
 * code for an access token.
 *
 * URL: GET /api/mcp-oauth-callback?code=...&state=...
 *
 * The `state` parameter encodes:
 *   { sessionId: string, nonce: string, oauthState?: string }
 *
 * The nonce prevents replay. The oauthState (if present) is the original
 * OAuth state value generated by the MCP SDK for CSRF protection.
 */

import type { RouteHandler } from "./types.js";
import { emitToRelaySession } from "../ws/sio-registry.js";

/** In-memory set of consumed nonces to prevent replay (cleared periodically). */
const consumedNonces = new Set<string>();

// Clean up old nonces every 10 minutes
setInterval(() => consumedNonces.clear(), 10 * 60 * 1000);

export const handleMcpOAuthRoute: RouteHandler = async (req, url) => {
    if (url.pathname !== "/api/mcp-oauth-callback") return undefined;
    if (req.method !== "GET") return undefined;

    const code = url.searchParams.get("code");
    const stateRaw = url.searchParams.get("state");
    const error = url.searchParams.get("error");

    // ── Error from OAuth provider ────────────────────────────────────────
    if (error) {
        const desc = url.searchParams.get("error_description") ?? error;
        return new Response(
            htmlPage("Authentication Failed", `<p>❌ ${escapeHtml(desc)}</p><p>You can close this tab.</p>`),
            { status: 400, headers: { "Content-Type": "text/html" } },
        );
    }

    // ── Parse state ──────────────────────────────────────────────────────
    if (!code || !stateRaw) {
        return new Response(
            htmlPage("Bad Request", "<p>Missing code or state parameter.</p>"),
            { status: 400, headers: { "Content-Type": "text/html" } },
        );
    }

    let state: { sessionId?: string; nonce?: string; oauthState?: string };
    try {
        state = JSON.parse(Buffer.from(stateRaw, "base64url").toString("utf-8"));
    } catch {
        return new Response(
            htmlPage("Bad Request", "<p>Invalid state parameter.</p>"),
            { status: 400, headers: { "Content-Type": "text/html" } },
        );
    }

    const { sessionId, nonce } = state;
    if (!sessionId || !nonce) {
        return new Response(
            htmlPage("Bad Request", "<p>Invalid state: missing sessionId or nonce.</p>"),
            { status: 400, headers: { "Content-Type": "text/html" } },
        );
    }

    // ── Replay protection ────────────────────────────────────────────────
    const nonceKey = `${sessionId}:${nonce}`;
    if (consumedNonces.has(nonceKey)) {
        return new Response(
            htmlPage("Already Used", "<p>This callback has already been processed.</p>"),
            { status: 409, headers: { "Content-Type": "text/html" } },
        );
    }

    // ── Forward to runner (cluster-wide via Redis adapter) ─────────────
    // In a multi-instance deployment, the OAuth callback may hit a different
    // server than the one owning the runner's relay socket. Emit to the
    // session room (broadcast via Redis) instead of looking up a local socket.
    consumedNonces.add(nonceKey);

    const emitted = emitToRelaySession(sessionId, "mcp_oauth_callback", {
        sessionId,
        nonce,
        code,
        oauthState: state.oauthState,
    });

    if (!emitted) {
        consumedNonces.delete(nonceKey); // Allow retry
        return new Response(
            htmlPage("Server Error", "<p>Relay not initialized. Please try again.</p>"),
            { status: 503, headers: { "Content-Type": "text/html" } },
        );
    }

    return new Response(
        htmlPage("Authentication Successful", `
            <p>✅ Authentication successful!</p>
            <p>You can close this tab and return to your session.</p>
            <script>setTimeout(() => window.close(), 2000);</script>
        `),
        { status: 200, headers: { "Content-Type": "text/html" } },
    );
};

// ── HTML helpers ─────────────────────────────────────────────────────────────

function escapeHtml(s: string): string {
    return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function htmlPage(title: string, body: string): string {
    return `<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>${escapeHtml(title)} — PizzaPi</title>
    <style>
        body { font-family: system-ui, sans-serif; max-width: 480px; margin: 80px auto; text-align: center; }
        h2 { margin-bottom: 0.5em; }
        p { color: #555; }
    </style>
</head>
<body>
    <h2>${escapeHtml(title)}</h2>
    ${body}
</body>
</html>`;
}
