import { describe, test, expect } from "bun:test";
import { readFileSync } from "fs";
import { join } from "path";
import { extractVapidFromCompose, extractSettingsFromCompose, resolveBetterAuthSecret } from "./web";

/**
 * Validates that the inlined COMPOSE_TEMPLATE in web.ts matches
 * the external compose.yml.template file, and that the template
 * produces valid YAML after substitution.
 */

// Mirror the inlined template from web.ts for validation.
const COMPOSE_TEMPLATE = `# Auto-generated by \`pizza web\` — regenerated on each run.
# For custom overrides, create a compose.override.yml next to this file.
services:
  redis:
    image: valkey/valkey:8-alpine
    command: ["valkey-server", "--save", "", "--appendonly", "no"]
    restart: unless-stopped

  server:
    build:
      context: {{REPO_PATH}}
      dockerfile: Dockerfile
    ports:
      - "{{PORT}}:7492"
    environment:
      - PORT=7492
      - PIZZAPI_REDIS_URL=redis://redis:6379
      - BETTER_AUTH_SECRET={{BETTER_AUTH_SECRET}}
      - VAPID_PUBLIC_KEY={{VAPID_PUBLIC_KEY}}
      - VAPID_PRIVATE_KEY={{VAPID_PRIVATE_KEY}}
      - VAPID_SUBJECT={{VAPID_SUBJECT}}
{{EXTRA_ORIGINS_LINE}}    volumes:
      - {{DATA_DIR}}:/app/data
    depends_on:
      - redis
    restart: unless-stopped
`;

describe("web.ts compose template", () => {
    test("inlined template matches external template file", () => {
        const externalPath = join(import.meta.dirname, "templates", "compose.yml.template");
        const external = readFileSync(externalPath, "utf-8");
        expect(COMPOSE_TEMPLATE).toBe(external);
    });

    test("template contains all required placeholders", () => {
        expect(COMPOSE_TEMPLATE).toContain("{{REPO_PATH}}");
        expect(COMPOSE_TEMPLATE).toContain("{{PORT}}");
        expect(COMPOSE_TEMPLATE).toContain("{{DATA_DIR}}");
        expect(COMPOSE_TEMPLATE).toContain("{{BETTER_AUTH_SECRET}}");
        expect(COMPOSE_TEMPLATE).toContain("{{VAPID_PUBLIC_KEY}}");
        expect(COMPOSE_TEMPLATE).toContain("{{VAPID_PRIVATE_KEY}}");
        expect(COMPOSE_TEMPLATE).toContain("{{VAPID_SUBJECT}}");
        expect(COMPOSE_TEMPLATE).toContain("{{EXTRA_ORIGINS_LINE}}");
    });

    test("template substitution produces valid compose structure", () => {
        const composed = COMPOSE_TEMPLATE
            .replace(/\{\{REPO_PATH}}/g, "/home/user/.pizzapi/web/repo")
            .replace(/\{\{PORT}}/g, "7492")
            .replace(/\{\{DATA_DIR}}/g, "/home/user/.pizzapi/web/data")
            .replace(/\{\{BETTER_AUTH_SECRET}}/g, "Secret123")
            .replace(/\{\{VAPID_PUBLIC_KEY}}/g, "BTestPublicKey123")
            .replace(/\{\{VAPID_PRIVATE_KEY}}/g, "TestPrivateKey456")
            .replace(/\{\{VAPID_SUBJECT}}/g, "mailto:admin@pizzapi.local")
            .replace(/\{\{EXTRA_ORIGINS_LINE}}/g, "      - PIZZAPI_EXTRA_ORIGINS=https://example.com\n");

        // No unsubstituted placeholders remain
        expect(composed).not.toContain("{{");
        expect(composed).not.toContain("}}");

        // Basic structural checks
        expect(composed).toContain("services:");
        expect(composed).toContain("redis:");
        expect(composed).toContain("server:");
        expect(composed).toContain('context: /home/user/.pizzapi/web/repo');
        expect(composed).toContain('"7492:7492"');
        expect(composed).toContain("BETTER_AUTH_SECRET=Secret123");
        expect(composed).toContain("VAPID_PUBLIC_KEY=BTestPublicKey123");
        expect(composed).toContain("VAPID_PRIVATE_KEY=TestPrivateKey456");
        expect(composed).toContain("VAPID_SUBJECT=mailto:admin@pizzapi.local");
        expect(composed).toContain("PIZZAPI_EXTRA_ORIGINS=https://example.com");
        expect(composed).toContain("/home/user/.pizzapi/web/data:/app/data");
    });

    test("template with no extra origins produces commented-out line", () => {
        const composed = COMPOSE_TEMPLATE
            .replace(/\{\{REPO_PATH}}/g, "/repo")
            .replace(/\{\{PORT}}/g, "7492")
            .replace(/\{\{DATA_DIR}}/g, "/data")
            .replace(/\{\{BETTER_AUTH_SECRET}}/g, "Secret")
            .replace(/\{\{VAPID_PUBLIC_KEY}}/g, "key")
            .replace(/\{\{VAPID_PRIVATE_KEY}}/g, "key")
            .replace(/\{\{VAPID_SUBJECT}}/g, "mailto:test@test.com")
            .replace(/\{\{EXTRA_ORIGINS_LINE}}/g, "      # - PIZZAPI_EXTRA_ORIGINS=\n");

        expect(composed).toContain("# - PIZZAPI_EXTRA_ORIGINS=");
        expect(composed).not.toContain("{{");
    });
});

// --- Migration tests ---

const FULL_COMPOSE = `services:
  redis:
    image: valkey/valkey:8-alpine
  server:
    ports:
      - "8080:7492"
    environment:
      - VAPID_PUBLIC_KEY=BRealPublicKeyABC123
      - VAPID_PRIVATE_KEY=RealPrivateKeyXYZ789
      - VAPID_SUBJECT=mailto:ops@example.com
      - BETTER_AUTH_SECRET=RealAuthSecret123
      - PIZZAPI_EXTRA_ORIGINS=https://my-tailscale.ts.net`;

describe("extractSettingsFromCompose", () => {
    test("extracts all settings from a fully configured compose file", () => {
        const result = extractSettingsFromCompose(FULL_COMPOSE);
        expect(result).toEqual({
            vapid: { publicKey: "BRealPublicKeyABC123", privateKey: "RealPrivateKeyXYZ789" },
            vapidSubject: "mailto:ops@example.com",
            extraOrigins: "https://my-tailscale.ts.net",
            port: 8080,
            betterAuthSecret: "RealAuthSecret123",
        });
    });

    test("returns empty object for template placeholders", () => {
        const template = FULL_COMPOSE
            .replace("BRealPublicKeyABC123", "{{VAPID_PUBLIC_KEY}}")
            .replace("RealPrivateKeyXYZ789", "{{VAPID_PRIVATE_KEY}}")
            .replace("mailto:ops@example.com", "{{VAPID_SUBJECT}}")
            .replace("RealAuthSecret123", "{{BETTER_AUTH_SECRET}}")
            .replace("https://my-tailscale.ts.net", "{{EXTRA_ORIGINS}}");
        const result = extractSettingsFromCompose(template);
        expect(result.vapid).toBeUndefined();
        expect(result.vapidSubject).toBeUndefined();
        expect(result.betterAuthSecret).toBeUndefined();
        expect(result.extraOrigins).toBeUndefined();
    });

    test("returns empty object when nothing is present", () => {
        const result = extractSettingsFromCompose("services:\n  redis:\n    image: valkey/valkey");
        expect(result).toEqual({});
    });

    test("handles trailing whitespace in values", () => {
        const content = "VAPID_PUBLIC_KEY=KeyA  \nVAPID_PRIVATE_KEY=KeyB  \n";
        const result = extractSettingsFromCompose(content);
        expect(result.vapid).toEqual({ publicKey: "KeyA", privateKey: "KeyB" });
    });

    test("skips commented-out PIZZAPI_EXTRA_ORIGINS", () => {
        const content = `    environment:
      - VAPID_PUBLIC_KEY=Key1
      - VAPID_PRIVATE_KEY=Key2
      # - PIZZAPI_EXTRA_ORIGINS=`;
        const result = extractSettingsFromCompose(content);
        expect(result.extraOrigins).toBeUndefined();
    });

    test("extracts port from host:container mapping", () => {
        const content = `    ports:\n      - "9000:7492"`;
        const result = extractSettingsFromCompose(content);
        expect(result.port).toBe(9000);
    });
});

describe("extractVapidFromCompose (backward compat)", () => {
    test("extracts VAPID keys", () => {
        const result = extractVapidFromCompose(FULL_COMPOSE);
        expect(result).toEqual({
            publicKey: "BRealPublicKeyABC123",
            privateKey: "RealPrivateKeyXYZ789",
        });
    });

    test("returns null when keys are missing", () => {
        expect(extractVapidFromCompose("services:\n  redis:\n    image: valkey/valkey")).toBeNull();
    });
});

describe("resolveBetterAuthSecret", () => {
    test("keeps existing secret", () => {
        const resolved = resolveBetterAuthSecret({
            currentSecret: "ExistingSecret",
            composeContents: ["- BETTER_AUTH_SECRET=FromCompose"],
            generate: () => "Generated",
        });
        expect(resolved).toEqual({ secret: "ExistingSecret", source: "existing" });
    });

    test("uses secret from compose content when missing", () => {
        const resolved = resolveBetterAuthSecret({
            currentSecret: "",
            composeContents: ["services:\n  server:\n    environment:\n      - BETTER_AUTH_SECRET=FromCompose"],
            generate: () => "Generated",
        });
        expect(resolved).toEqual({ secret: "FromCompose", source: "compose" });
    });

    test("prefers override compose content (first) when missing", () => {
        const resolved = resolveBetterAuthSecret({
            currentSecret: "",
            composeContents: ["- BETTER_AUTH_SECRET=FromOverride", "- BETTER_AUTH_SECRET=FromCompose"],
            generate: () => "Generated",
        });
        expect(resolved).toEqual({ secret: "FromOverride", source: "compose" });
    });

    test("ignores commented-out secret lines", () => {
        const resolved = resolveBetterAuthSecret({
            currentSecret: "",
            composeContents: ["# - BETTER_AUTH_SECRET=Nope"],
            generate: () => "Generated",
        });
        expect(resolved).toEqual({ secret: "Generated", source: "generated" });
    });
});
