import { describe, test, expect } from "bun:test";
import { readFileSync, mkdirSync, writeFileSync } from "fs";
import { join } from "path";
import { mkdtempSync } from "fs";
import { tmpdir } from "os";
import {
    extractVapidFromCompose,
    extractSettingsFromCompose,
    findRepoRoot,
    getCliVersion,
    parseArgs,
    resolveBetterAuthSecret,
    resolveMissingProxySettings,
    shouldInstallDependencies,
    shouldRebuildHostUi,
    readBooleanEnv,
    getDockerPlatform,
    ensureComposeSucceeded,
} from "./web";

/**
 * Validates that the inlined COMPOSE_TEMPLATE in web.ts matches
 * the external compose.yml.template file, and that the template
 * produces valid YAML after substitution.
 */

// Mirror the inlined template from web.ts for validation.
const COMPOSE_TEMPLATE = `# Auto-generated by \`pizza web\` — regenerated on each run.
# For custom overrides, create a compose.override.yml next to this file.
services:
  redis:
    image: redis:7-alpine
{{REDIS_PLATFORM_LINE}}    command: ["redis-server", "--save", "", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

{{APP_SERVICE_BLOCK}}{{VOLUMES_SECTION}}`;

describe("web.ts compose template", () => {
    test("inlined template matches external template file", () => {
        // Always look in src/templates/ so this test passes when bun discovers
        // the compiled dist/web.test.js from the project root as well as when
        // running directly from packages/cli/src/web.test.ts.
        const externalPath = join(import.meta.dirname, "..", "src", "templates", "compose.yml.template");
        const external = readFileSync(externalPath, "utf-8");
        expect(COMPOSE_TEMPLATE).toBe(external);
    });

    test("template contains all required placeholders", () => {
        expect(COMPOSE_TEMPLATE).toContain("{{REDIS_PLATFORM_LINE}}");
        expect(COMPOSE_TEMPLATE).toContain("{{APP_SERVICE_BLOCK}}");
        expect(COMPOSE_TEMPLATE).toContain("{{VOLUMES_SECTION}}");
        expect(COMPOSE_TEMPLATE).not.toContain("{{UI_SERVICE_BLOCK}}");
        expect(COMPOSE_TEMPLATE).not.toContain("{{UI_VOLUME_LINE}}");
        expect(COMPOSE_TEMPLATE).not.toContain("{{UI_DEPENDS_ON_LINE}}");
    });

    test("template substitution produces dev compose structure", () => {
        const devBlock = `  dev:\n    build:\n      context: /home/user/.pizzapi/web/repo\n      dockerfile: Dockerfile\n      target: builder\n    command: bun run dev\n    ports:\n      - "7492:7492"\n      - "5173:5173"\n    environment:\n      - PORT=7492\n      - PIZZAPI_REDIS_URL=redis://redis:6379\n      - BETTER_AUTH_SECRET=Secret123\n      - AUTH_DB_PATH=/app/data/auth.db\n      - VAPID_PUBLIC_KEY=BTestPublicKey123\n      - VAPID_PRIVATE_KEY=TestPrivateKey456\n      - VAPID_SUBJECT=mailto:admin@pizzapi.local\n      - PIZZAPI_EXTRA_ORIGINS=https://example.com\n      # - PIZZAPI_TRUST_PROXY=\n      # - PIZZAPI_PROXY_DEPTH=\n    volumes:\n      - /home/user/.pizzapi/web/repo:/app:Z\n      - /app/node_modules\n      - /home/user/.pizzapi/web/data:/app/data:Z\n    depends_on:\n      redis:\n        condition: service_healthy\n    restart: unless-stopped\n    stop_grace_period: 30s\n\n`;
        const composed = COMPOSE_TEMPLATE
            .replace(/\{\{REDIS_PLATFORM_LINE}}/g, "    platform: linux/arm64\n")
            .replace(/\{\{APP_SERVICE_BLOCK}}/g, devBlock)
            .replace(/\{\{VOLUMES_SECTION}}/g, "");

        expect(composed).not.toContain("{{");
        expect(composed).not.toContain("}}");
        expect(composed).toContain("services:");
        expect(composed).toContain("redis:");
        expect(composed).toContain("redis-cli");
        expect(composed).toContain("dev:");
        expect(composed).toContain('target: builder');
        expect(composed).toContain('command: bun run dev');
        expect(composed).toContain('"7492:7492"');
        expect(composed).toContain('"5173:5173"');
        expect(composed).toContain("BETTER_AUTH_SECRET=Secret123");
        expect(composed).toContain("VAPID_PUBLIC_KEY=BTestPublicKey123");
        expect(composed).toContain("VAPID_PRIVATE_KEY=TestPrivateKey456");
        expect(composed).toContain("VAPID_SUBJECT=mailto:admin@pizzapi.local");
        expect(composed).toContain("PIZZAPI_EXTRA_ORIGINS=https://example.com");
        expect(composed).toContain("AUTH_DB_PATH=/app/data/auth.db");
        expect(composed).toContain("/home/user/.pizzapi/web/data:/app/data:Z");
        expect(composed).toContain("/home/user/.pizzapi/web/repo:/app:Z");
        expect(composed).toContain("/app/node_modules");
    });

    test("template substitution produces prod compose structure", () => {
        const prodBlock = `  ui:\n    image: ghcr.io/pizzaface/pizzapi-ui:latest\n    pull_policy: always\n    command: ["/bin/sh", "-c", "rm -rf /ui-dist/* && cp -a /usr/share/nginx/html/. /ui-dist/ && tail -f /dev/null"]\n    volumes:\n      - ui-dist:/ui-dist\n    healthcheck:\n      test: ["CMD", "test", "-f", "/ui-dist/index.html"]\n      interval: 10s\n      timeout: 5s\n      retries: 5\n    restart: unless-stopped\n\n  server:\n    build:\n      context: /home/user/.pizzapi/web/repo\n      dockerfile: Dockerfile\n      target: runtime-no-ui\n      args:\n        PREBUILT_UI: "true"\n        UI_DIST_HASH: "abc123def456"\n    ports:\n      - "7492:7492"\n    environment:\n      - PORT=7492\n      - PIZZAPI_REDIS_URL=redis://redis:6379\n      - BETTER_AUTH_SECRET=Secret123\n      - VAPID_PUBLIC_KEY=BTestPublicKey123\n      - VAPID_PRIVATE_KEY=TestPrivateKey456\n      - VAPID_SUBJECT=mailto:admin@pizzapi.local\n      - PIZZAPI_EXTRA_ORIGINS=https://example.com\n      # - PIZZAPI_TRUST_PROXY=\n      # - PIZZAPI_PROXY_DEPTH=\n    volumes:\n      - /home/user/.pizzapi/web/data:/app/data:Z\n      - ui-dist:/app/packages/ui/dist:ro\n    depends_on:\n      redis:\n        condition: service_started\n      ui:\n        condition: service_healthy\n    restart: unless-stopped\n    stop_grace_period: 30s\n\n`;
        const composed = COMPOSE_TEMPLATE
            .replace(/\{\{REDIS_PLATFORM_LINE}}/g, "    platform: linux/arm64\n")
            .replace(/\{\{APP_SERVICE_BLOCK}}/g, prodBlock)
            .replace(/\{\{VOLUMES_SECTION}}/g, "volumes:\n  ui-dist:\n");

        expect(composed).not.toContain("{{");
        expect(composed).not.toContain("}}");
        expect(composed).toContain('target: runtime-no-ui');
        expect(composed).toContain('redis-cli');
        expect(composed).toContain('image: ghcr.io/pizzaface/pizzapi-ui:latest');
        expect(composed).toContain('ui-dist:/app/packages/ui/dist:ro');
        expect(composed).toContain('PREBUILT_UI: "true"');
        expect(composed).toContain('UI_DIST_HASH: "abc123def456"');
    });

    test("template with no extra origins produces commented-out line", () => {
        const devBlock = `  dev:\n    build:\n      context: /repo\n      dockerfile: Dockerfile\n      target: builder\n    command: bun run dev\n    ports:\n      - "7492:7492"\n      - "5173:5173"\n    environment:\n      - PORT=7492\n      - PIZZAPI_REDIS_URL=redis://redis:6379\n      - BETTER_AUTH_SECRET=Secret\n      - VAPID_PUBLIC_KEY=key\n      - VAPID_PRIVATE_KEY=key\n      - VAPID_SUBJECT=mailto:test@test.com\n      # - PIZZAPI_EXTRA_ORIGINS=\n      # - PIZZAPI_TRUST_PROXY=\n      # - PIZZAPI_PROXY_DEPTH=\n    volumes:\n      - /repo:/app:Z\n      - /app/node_modules\n      - /data:/app/data:Z\n    depends_on:\n      redis:\n        condition: service_healthy\n    restart: unless-stopped\n    stop_grace_period: 30s\n\n`;
        const composed = COMPOSE_TEMPLATE
            .replace(/\{\{REDIS_PLATFORM_LINE}}/g, "    platform: linux/amd64\n")
            .replace(/\{\{APP_SERVICE_BLOCK}}/g, devBlock)
            .replace(/\{\{VOLUMES_SECTION}}/g, "");

        expect(composed).toContain("# - PIZZAPI_EXTRA_ORIGINS=");
        expect(composed).toContain("redis-cli");
        expect(composed).not.toContain("{{");
    });
});

describe("shouldInstallDependencies", () => {
    test("requires install when node_modules missing", () => {
        expect(
            shouldInstallDependencies({
                nodeModulesPresent: false,
                currentLockHash: "abc",
                lastLockHash: "abc",
            })
        ).toBe(true);
    });

    test("skips install when hashes match", () => {
        expect(
            shouldInstallDependencies({
                nodeModulesPresent: true,
                currentLockHash: "abc",
                lastLockHash: "abc",
            })
        ).toBe(false);
    });

    test("installs when lock hash changed", () => {
        expect(
            shouldInstallDependencies({
                nodeModulesPresent: true,
                currentLockHash: "new",
                lastLockHash: "old",
            })
        ).toBe(true);
    });
});

describe("shouldRebuildHostUi", () => {
    test("rebuilds when dist missing", () => {
        expect(
            shouldRebuildHostUi({
                distReady: false,
                currentSignature: "sig",
                lastSignature: "sig",
            })
        ).toBe(true);
    });

    test("skips rebuild when signature unchanged", () => {
        expect(
            shouldRebuildHostUi({
                distReady: true,
                currentSignature: "sig",
                lastSignature: "sig",
            })
        ).toBe(false);
    });

    test("rebuilds when signature missing", () => {
        expect(
            shouldRebuildHostUi({
                distReady: true,
                currentSignature: null,
                lastSignature: "sig",
            })
        ).toBe(true);
    });
});

describe("readBooleanEnv", () => {
    test("falls back to default when undefined", () => {
        expect(readBooleanEnv(undefined, true)).toBe(true);
    });

    test("parses truthy strings", () => {
        expect(readBooleanEnv("YES", false)).toBe(true);
        expect(readBooleanEnv("1", false)).toBe(true);
    });

    test("parses falsy strings", () => {
        expect(readBooleanEnv("no", true)).toBe(false);
        expect(readBooleanEnv("0", true)).toBe(false);
    });

    test("returns default for unknown values", () => {
        expect(readBooleanEnv("maybe", true)).toBe(true);
    });
});
// --- Migration tests ---

const FULL_COMPOSE = `services:
  redis:
    image: redis:7-alpine
  server:
    ports:
      - "8080:7492"
    environment:
      - VAPID_PUBLIC_KEY=BRealPublicKeyABC123
      - VAPID_PRIVATE_KEY=RealPrivateKeyXYZ789
      - VAPID_SUBJECT=mailto:ops@example.com
      - BETTER_AUTH_SECRET=RealAuthSecret123
      - PIZZAPI_EXTRA_ORIGINS=https://my-tailscale.ts.net`;

describe("extractSettingsFromCompose", () => {
    test("extracts all settings from a fully configured compose file", () => {
        const result = extractSettingsFromCompose(FULL_COMPOSE);
        expect(result).toEqual({
            vapid: { publicKey: "BRealPublicKeyABC123", privateKey: "RealPrivateKeyXYZ789" },
            vapidSubject: "mailto:ops@example.com",
            extraOrigins: "https://my-tailscale.ts.net",
            port: 8080,
            betterAuthSecret: "RealAuthSecret123",
        });
    });

    test("returns empty object for template placeholders", () => {
        const template = FULL_COMPOSE
            .replace("BRealPublicKeyABC123", "{{VAPID_PUBLIC_KEY}}")
            .replace("RealPrivateKeyXYZ789", "{{VAPID_PRIVATE_KEY}}")
            .replace("mailto:ops@example.com", "{{VAPID_SUBJECT}}")
            .replace("RealAuthSecret123", "{{BETTER_AUTH_SECRET}}")
            .replace("https://my-tailscale.ts.net", "{{EXTRA_ORIGINS}}");
        const result = extractSettingsFromCompose(template);
        expect(result.vapid).toBeUndefined();
        expect(result.vapidSubject).toBeUndefined();
        expect(result.betterAuthSecret).toBeUndefined();
        expect(result.extraOrigins).toBeUndefined();
    });

    test("returns empty object when nothing is present", () => {
        const result = extractSettingsFromCompose("services:\n  redis:\n    image: redis");
        expect(result).toEqual({});
    });

    test("handles trailing whitespace in values", () => {
        const content = "VAPID_PUBLIC_KEY=KeyA  \nVAPID_PRIVATE_KEY=KeyB  \n";
        const result = extractSettingsFromCompose(content);
        expect(result.vapid).toEqual({ publicKey: "KeyA", privateKey: "KeyB" });
    });

    test("skips commented-out PIZZAPI_EXTRA_ORIGINS", () => {
        const content = `    environment:
      - VAPID_PUBLIC_KEY=Key1
      - VAPID_PRIVATE_KEY=Key2
      # - PIZZAPI_EXTRA_ORIGINS=`;
        const result = extractSettingsFromCompose(content);
        expect(result.extraOrigins).toBeUndefined();
    });

    test("extracts port from host:container mapping", () => {
        const content = `    ports:\n      - "9000:7492"`;
        const result = extractSettingsFromCompose(content);
        expect(result.port).toBe(9000);
    });

    test("parses YAML mapping syntax for proxy settings (double-quoted)", () => {
        // This is the format shown in self-hosting docs and produced by standard
        // YAML tools — the compose.override.yml uses mapping form, not list form.
        const content = `services:
  server:
    environment:
      PIZZAPI_TRUST_PROXY: "true"
      PIZZAPI_PROXY_DEPTH: "1"`;
        const result = extractSettingsFromCompose(content);
        expect(result.trustProxy).toBe(true);
        expect(result.proxyDepth).toBe(1);
    });

    test("parses YAML mapping syntax for proxy settings (single-quoted)", () => {
        const content = `services:
  server:
    environment:
      PIZZAPI_TRUST_PROXY: 'false'
      PIZZAPI_PROXY_DEPTH: '2'`;
        const result = extractSettingsFromCompose(content);
        expect(result.trustProxy).toBe(false);
        expect(result.proxyDepth).toBe(2);
    });

    test("parses YAML mapping syntax for proxy settings (unquoted)", () => {
        const content = `services:
  server:
    environment:
      PIZZAPI_TRUST_PROXY: true
      PIZZAPI_PROXY_DEPTH: 1`;
        const result = extractSettingsFromCompose(content);
        expect(result.trustProxy).toBe(true);
        expect(result.proxyDepth).toBe(1);
    });

    test("strips inline YAML comments from proxy settings", () => {
        const content = `services:
  server:
    environment:
      PIZZAPI_TRUST_PROXY: "true" # Caddy
      PIZZAPI_PROXY_DEPTH: "1" # trusted hop count`;
        const result = extractSettingsFromCompose(content);
        expect(result.trustProxy).toBe(true);
        expect(result.proxyDepth).toBe(1);
    });

    test("parses YAML mapping syntax for all env vars", () => {
        const content = `services:
  server:
    ports:
      - "8080:7492"
    environment:
      VAPID_PUBLIC_KEY: "MapPubKey123"
      VAPID_PRIVATE_KEY: "MapPrivKey456"
      VAPID_SUBJECT: "mailto:map@example.com"
      BETTER_AUTH_SECRET: "MapSecret789"
      PIZZAPI_EXTRA_ORIGINS: "https://map.example.com"
      PIZZAPI_TRUST_PROXY: "true"
      PIZZAPI_PROXY_DEPTH: "2"`;
        const result = extractSettingsFromCompose(content);
        expect(result.vapid).toEqual({ publicKey: "MapPubKey123", privateKey: "MapPrivKey456" });
        expect(result.vapidSubject).toBe("mailto:map@example.com");
        expect(result.betterAuthSecret).toBe("MapSecret789");
        expect(result.extraOrigins).toBe("https://map.example.com");
        expect(result.port).toBe(8080);
        expect(result.trustProxy).toBe(true);
        expect(result.proxyDepth).toBe(2);
    });

    test("list form still takes priority over mapping form", () => {
        // When both forms exist, list form regex matches first (realistic edge case)
        const content = `    environment:
      - PIZZAPI_TRUST_PROXY=true
      PIZZAPI_TRUST_PROXY: "false"`;
        const result = extractSettingsFromCompose(content);
        expect(result.trustProxy).toBe(true);
    });
});

describe("extractVapidFromCompose (backward compat)", () => {
    test("extracts VAPID keys", () => {
        const result = extractVapidFromCompose(FULL_COMPOSE);
        expect(result).toEqual({
            publicKey: "BRealPublicKeyABC123",
            privateKey: "RealPrivateKeyXYZ789",
        });
    });

    test("returns null when keys are missing", () => {
        expect(extractVapidFromCompose("services:\n  redis:\n    image: redis")).toBeNull();
    });
});

describe("resolveBetterAuthSecret", () => {
    test("keeps existing secret", () => {
        const resolved = resolveBetterAuthSecret({
            currentSecret: "ExistingSecret",
            composeContents: ["- BETTER_AUTH_SECRET=FromCompose"],
            generate: () => "Generated",
        });
        expect(resolved).toEqual({ secret: "ExistingSecret", source: "existing" });
    });

    test("uses secret from compose content when missing", () => {
        const resolved = resolveBetterAuthSecret({
            currentSecret: "",
            composeContents: ["services:\n  server:\n    environment:\n      - BETTER_AUTH_SECRET=FromCompose"],
            generate: () => "Generated",
        });
        expect(resolved).toEqual({ secret: "FromCompose", source: "compose" });
    });

    test("prefers override compose content (first) when missing", () => {
        const resolved = resolveBetterAuthSecret({
            currentSecret: "",
            composeContents: ["- BETTER_AUTH_SECRET=FromOverride", "- BETTER_AUTH_SECRET=FromCompose"],
            generate: () => "Generated",
        });
        expect(resolved).toEqual({ secret: "FromOverride", source: "compose" });
    });

    test("ignores commented-out secret lines", () => {
        const resolved = resolveBetterAuthSecret({
            currentSecret: "",
            composeContents: ["# - BETTER_AUTH_SECRET=Nope"],
            generate: () => "Generated",
        });
        expect(resolved).toEqual({ secret: "Generated", source: "generated" });
    });
});

describe("findRepoRoot", () => {
    test("finds this repo when called from within it", () => {
        // import.meta.dirname is inside packages/cli/src, which is within the repo —
        // so the binary-dir walk should discover it.
        const root = findRepoRoot();
        expect(root).not.toBeNull();
        // Sanity-check the returned path contains both marker files
        const { existsSync } = require("fs");
        expect(existsSync(join(root!, "Dockerfile"))).toBe(true);
        expect(existsSync(join(root!, "docker", "compose.yml"))).toBe(true);
    });

    test("returns null when no marker files exist in any ancestor", () => {
        // Use a temp dir that has no Dockerfile / docker/compose.yml
        const tmp = mkdtempSync(join(tmpdir(), "pizza-test-"));
        const origCwd = process.cwd();
        try {
            process.chdir(tmp);
            // import.meta.dirname still points inside the repo, so we need to
            // confirm the function returns a real result OR that the CWD walk
            // doesn't incorrectly report the temp dir as a repo root.
            // The actual assertion here is that a directory with no markers
            // never gets returned when the CWD walk hits it exclusively.
            // We can verify this by checking that if we create a subdir without
            // markers the function still finds the real repo (via binary dir walk).
            const result = findRepoRoot();
            // The repo is still findable via import.meta.dirname walk
            expect(result).not.toBeNull();
        } finally {
            process.chdir(origCwd);
        }
    });

    test("finds repo when CWD is the repo root (simulates global binary)", () => {
        // Simulate: import.meta.dirname is a temp dir (global bin), but CWD is the repo root.
        // We can't fully mock import.meta.dirname, but we can verify that CWD=repo-root
        // produces the same result as normal detection.
        const origCwd = process.cwd();
        try {
            // findRepoRoot() without module-dir walk would still find it via CWD if
            // CWD is inside the repo. Change to repo root and confirm detection works.
            const root = findRepoRoot();
            expect(root).not.toBeNull();

            // Now change CWD to repo root and check result is consistent
            process.chdir(root!);
            const rootFromRepoDir = findRepoRoot();
            expect(rootFromRepoDir).toBe(root);
        } finally {
            process.chdir(origCwd);
        }
    });
});

describe("resolveMissingProxySettings", () => {
    test("keeps existing proxy settings", () => {
        const resolved = resolveMissingProxySettings({
            currentTrustProxy: false,
            currentProxyDepth: 0,
            composeContents: ["- PIZZAPI_TRUST_PROXY=true\n- PIZZAPI_PROXY_DEPTH=3"],
        });
        expect(resolved).toEqual({
            trustProxy: false,
            proxyDepth: 0,
            source: "existing",
        });
    });

    test("backfills missing trustProxy and proxyDepth from compose", () => {
        const resolved = resolveMissingProxySettings({
            currentTrustProxy: undefined,
            currentProxyDepth: undefined,
            composeContents: ["- PIZZAPI_TRUST_PROXY=true\n- PIZZAPI_PROXY_DEPTH=1"],
        });
        expect(resolved).toEqual({
            trustProxy: true,
            proxyDepth: 1,
            source: "compose",
        });
    });

    test("uses override compose first and fills only missing fields", () => {
        const resolved = resolveMissingProxySettings({
            currentTrustProxy: undefined,
            currentProxyDepth: 2,
            composeContents: ["- PIZZAPI_TRUST_PROXY=false", "- PIZZAPI_TRUST_PROXY=true\n- PIZZAPI_PROXY_DEPTH=1"],
        });
        expect(resolved).toEqual({
            trustProxy: false,
            proxyDepth: 2,
            source: "compose",
        });
    });
});

describe("ensureComposeSucceeded", () => {
    test("does nothing for exit code 0", () => {
        expect(() => ensureComposeSucceeded(0, "starting web")).not.toThrow();
    });

    test("throws a helpful error for non-zero exit codes", () => {
        expect(() => ensureComposeSucceeded(18, "starting web")).toThrow(
            "docker compose failed while starting web (exit code 18)",
        );
    });

    test("normalizes null/undefined exit codes to 1", () => {
        expect(() => ensureComposeSucceeded(null as unknown as number, "pulling ui image")).toThrow(
            "docker compose failed while pulling ui image (exit code 1)",
        );
        expect(() => ensureComposeSucceeded(undefined as unknown as number, "pulling ui image")).toThrow(
            "docker compose failed while pulling ui image (exit code 1)",
        );
    });
});

describe("parseArgs", () => {
    test("defaults: latest tag, local build off, dev ui off, detach true, noCache false, help false", () => {
        const r = parseArgs([]);
        expect(r.tag).toBe("latest");
        expect(r.build).toBe(false);
        expect(r.devUi).toBe(false);
        expect(r.detach).toBe(true);
        expect(r.noCache).toBe(false);
        expect(r.help).toBe(false);
    });

    test("--tag sets image tag", () => {
        const r = parseArgs(["--tag", "main"]);
        expect(r.tag).toBe("main");
    });

    test("--build enables local build mode", () => {
        const r = parseArgs(["--build"]);
        expect(r.build).toBe(true);
    });

    test("--dev-ui enables local dev ui mode", () => {
        const r = parseArgs(["--dev-ui"]);
        expect(r.devUi).toBe(true);
    });

    test("--no-cache sets noCache", () => {
        const r = parseArgs(["--no-cache"]);
        expect(r.noCache).toBe(true);
    });

    test("--foreground disables detach", () => {
        expect(parseArgs(["--foreground"]).detach).toBe(false);
        expect(parseArgs(["-f"]).detach).toBe(false);
    });

    test("--port parses port number", () => {
        expect(parseArgs(["--port", "8080"]).port).toBe(8080);
    });

    test("combines multiple flags", () => {
        const r = parseArgs(["--no-cache", "-f", "--port", "9000", "--tag", "sha123", "--build", "--dev-ui"]);
        expect(r.noCache).toBe(true);
        expect(r.detach).toBe(false);
        expect(r.port).toBe(9000);
        expect(r.tag).toBe("sha123");
        expect(r.build).toBe(true);
        expect(r.devUi).toBe(true);
    });
});

describe("getCliVersion", () => {
    test("returns a semver-like version string from package.json", () => {
        const version = getCliVersion();
        // Should be a non-empty string that looks like a version
        expect(typeof version).toBe("string");
        expect(version.length).toBeGreaterThan(0);
        // Should match semver pattern (possibly with prerelease suffix)
        expect(version).toMatch(/^\d+\.\d+\.\d+/);
    });

    test("does not return 'latest'", () => {
        // When running from the repo, package.json always has a real version
        expect(getCliVersion()).not.toBe("latest");
    });
});

describe("getDockerPlatform", () => {
    test("returns linux/arm64 for arm64", () => {
        expect(getDockerPlatform("arm64")).toBe("linux/arm64");
    });

    test("returns linux/amd64 for x64", () => {
        expect(getDockerPlatform("x64")).toBe("linux/amd64");
    });

    test("returns linux/arm/v7 for arm", () => {
        expect(getDockerPlatform("arm")).toBe("linux/arm/v7");
    });

    test("defaults to linux/amd64 for unknown architectures", () => {
        expect(getDockerPlatform("riscv64")).toBe("linux/amd64");
        expect(getDockerPlatform("")).toBe("linux/amd64");
    });

    test("uses current host arch when called with no argument", () => {
        const result = getDockerPlatform();
        expect(result).toMatch(/^linux\//);
    });
});
