#!/usr/bin/env bun
/**
 * compile-prompt.ts — Build-time Handlebars precompilation.
 *
 * Reads .hbs template + partials from src/config/templates/,
 * resolves partials inline, precompiles via Handlebars, and writes
 * a TypeScript module that exports the precompiled template spec.
 *
 * Output: src/config/system-prompt.precompiled.ts
 *
 * Run: `bun scripts/compile-prompt.ts`
 * Wired as the `prebuild` script in package.json.
 */
import Handlebars from "handlebars";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, basename, extname } from "node:path";

const TEMPLATES_DIR = join(import.meta.dir, "..", "src", "config", "templates");
const PARTIALS_DIR = join(TEMPLATES_DIR, "partials");
const OUTPUT_FILE = join(import.meta.dir, "..", "src", "config", "system-prompt.precompiled.ts");
const PROVIDER_TEMPLATE = join(TEMPLATES_DIR, "claude-code-provider.hbs");
const PROVIDER_OUTPUT_FILE = join(import.meta.dir, "..", "src", "config", "claude-code-provider.precompiled.ts");

// ── Load partials ──────────────────────────────────────────────────────────
const partials: Record<string, string> = {};
try {
    const partialFiles = readdirSync(PARTIALS_DIR).filter((f) => f.endsWith(".hbs"));
    for (const file of partialFiles) {
        const name = basename(file, extname(file));
        partials[name] = readFileSync(join(PARTIALS_DIR, file), "utf-8");
    }
} catch (err) {
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
}

// ── Inline partials into main template ─────────────────────────────────────
// Replace {{> partial-name}} with the partial content so the precompiled
// output is self-contained — no runtime partial registration needed.
let templateSource = readFileSync(join(TEMPLATES_DIR, "system-prompt.hbs"), "utf-8");
for (const [name, content] of Object.entries(partials)) {
    const partialRegex = new RegExp(`\\{\\{>\\s*${name}\\s*\\}\\}`, "g");
    templateSource = templateSource.replace(partialRegex, content);
}

// Verify no unresolved partials remain
const unresolvedPartials = templateSource.match(/\{\{>\s*[\w-]+\s*\}\}/g);
if (unresolvedPartials) {
    console.error(`✗ Unresolved partials in template: ${unresolvedPartials.join(", ")}`);
    process.exit(1);
}

// ── Precompile ─────────────────────────────────────────────────────────────
const precompiledSpec = Handlebars.precompile(templateSource);

// ── Write output module ────────────────────────────────────────────────────
const output = `// @ts-nocheck — generated Handlebars runtime code is untyped
// AUTO-GENERATED by scripts/compile-prompt.ts — do not edit manually.
// Source: src/config/templates/system-prompt.hbs
// Re-run: bun scripts/compile-prompt.ts

import Handlebars from "handlebars";

// Precompiled template spec (partials inlined at build time)
const spec = Handlebars.template(${precompiledSpec});

/** Context variables available in the system prompt template. */
export interface SystemPromptContext {
    /** Current date and time, e.g. "March 29, 2026, 3:45 PM" */
    dateTime: string;
    /** Current git branch name, e.g. "feat/my-feature" */
    gitBranch?: string;
    /** Git worktree root path (if running inside a worktree) */
    gitWorktree?: string;
    /** Current working directory */
    cwd?: string;
    /** Whether running inside a PizzaPi runner (enables runner-only sections) */
    isRunner?: boolean;
}

/**
 * Render the built-in system prompt with the given context.
 *
 * The template is precompiled at build time from .hbs source files.
 * Only the lightweight Handlebars runtime is needed here.
 */
export function renderSystemPrompt(ctx: SystemPromptContext): string {
    return spec(ctx);
}
`;

writeFileSync(OUTPUT_FILE, output, "utf-8");
console.log(`✓ Precompiled system prompt → ${OUTPUT_FILE}`);

// ── Precompile Claude Code provider prompt ─────────────────────────────────
let providerTemplateSource = readFileSync(PROVIDER_TEMPLATE, "utf-8");
// Inline partials (same as main template)
for (const [name, content] of Object.entries(partials)) {
    const partialRegex = new RegExp(`\\{\\{>\\s*${name}\\s*\\}\\}`, "g");
    providerTemplateSource = providerTemplateSource.replace(partialRegex, content);
}

const providerPrecompiledSpec = Handlebars.precompile(providerTemplateSource);

const providerOutput = `// @ts-nocheck — generated Handlebars runtime code is untyped
// AUTO-GENERATED by scripts/compile-prompt.ts — do not edit manually.
// Source: src/config/templates/claude-code-provider.hbs
// Re-run: bun scripts/compile-prompt.ts

import Handlebars from "handlebars";

// Precompiled template spec (partials inlined at build time)
const spec = Handlebars.template(${providerPrecompiledSpec});

/** Context variables for the Claude Code provider system prompt. */
export interface ClaudeCodeProviderContext {
    /** Current working directory */
    cwd?: string;
    /** Current git branch name */
    gitBranch?: string;
    /** Platform name, e.g. "darwin", "linux" */
    platform: string;
    /** Shell name, e.g. "zsh", "bash" */
    shell: string;
    /** OS version string */
    osVersion: string;
}

/**
 * Render the Claude Code provider system prompt with the given context.
 *
 * Used when Claude Code Provider mode is enabled to replace the base
 * system prompt with the real Claude Code system prompt.
 */
export function renderClaudeCodeProviderPrompt(ctx: ClaudeCodeProviderContext): string {
    return spec(ctx);
}
`;

writeFileSync(PROVIDER_OUTPUT_FILE, providerOutput, "utf-8");
console.log(`✓ Precompiled Claude Code provider prompt → ${PROVIDER_OUTPUT_FILE}`);
