import { mkdir, rm, access } from "node:fs/promises";
import path from "node:path";
import { getKysely } from "../auth.js";

export interface StoredAttachment {
    attachmentId: string;
    sessionId: string;
    ownerUserId: string;
    uploaderUserId: string;
    filename: string;
    mimeType: string;
    size: number;
    createdAt: string;
    expiresAt: string;
    expiresAtMs?: number;
    filePath: string;
}

const DEFAULT_ATTACHMENT_TTL_MS = 15 * 60 * 1000;
const DEFAULT_MAX_FILE_SIZE_BYTES = 20 * 1024 * 1024;
/** Extracted images (from session state) persist for 24 hours. */
const EXTRACTED_IMAGE_TTL_MS = 24 * 60 * 60 * 1000;

function attachmentTtlMs(): number {
    const raw = Number.parseInt(process.env.PIZZAPI_ATTACHMENT_TTL_MS ?? "", 10);
    return Number.isFinite(raw) && raw > 0 ? raw : DEFAULT_ATTACHMENT_TTL_MS;
}

export function attachmentMaxFileSizeBytes(): number {
    const raw = Number.parseInt(process.env.PIZZAPI_ATTACHMENT_MAX_FILE_SIZE_BYTES ?? "", 10);
    return Number.isFinite(raw) && raw > 0 ? raw : DEFAULT_MAX_FILE_SIZE_BYTES;
}

const uploadRoot = path.resolve(process.env.PIZZAPI_ATTACHMENT_DIR ?? path.join(process.cwd(), ".pizzapi", "uploads"));

const attachments = new Map<string, StoredAttachment>();

export function sanitizeFilename(filename: string): string {
    return filename.replace(/[^a-zA-Z0-9._-]/g, "_");
}

export async function storeSessionAttachment(input: {
    sessionId: string;
    ownerUserId: string;
    uploaderUserId: string;
    file: File;
}): Promise<StoredAttachment> {
    const { sessionId, ownerUserId, uploaderUserId, file } = input;

    const attachmentId = crypto.randomUUID();
    const createdAtMs = Date.now();
    const expiresAtMs = createdAtMs + attachmentTtlMs();

    const safeName = sanitizeFilename(file.name || `attachment-${attachmentId}`);
    const targetPath = path.join(uploadRoot, `${attachmentId}-${safeName}`);

    await mkdir(uploadRoot, { recursive: true });
    const bytes = new Uint8Array(await file.arrayBuffer());
    await Bun.write(targetPath, bytes);

    const record: StoredAttachment = {
        attachmentId,
        sessionId,
        ownerUserId,
        uploaderUserId,
        filename: file.name || safeName,
        mimeType: file.type || "application/octet-stream",
        size: file.size,
        createdAt: new Date(createdAtMs).toISOString(),
        expiresAt: new Date(expiresAtMs).toISOString(),
        expiresAtMs,
        filePath: targetPath,
    };

    attachments.set(attachmentId, record);
    return record;
}

export function getStoredAttachment(attachmentId: string): StoredAttachment | null {
    const record = attachments.get(attachmentId);
    if (!record) return null;

    const expiresAtMs = record.expiresAtMs ?? Date.parse(record.expiresAt);
    if (expiresAtMs <= Date.now()) {
        void deleteStoredAttachment(attachmentId);
        return null;
    }

    return record;
}

export async function deleteStoredAttachment(attachmentId: string): Promise<void> {
    const record = attachments.get(attachmentId);
    if (!record) return;
    attachments.delete(attachmentId);
    try {
        await rm(record.filePath, { force: true });
    } catch {}
    void removePersistedAttachment(attachmentId).catch(() => {});
}

// ── Extracted image storage ──────────────────────────────────────────────────
// Used by strip-images.ts to offload inline base64 images from session state
// payloads. Uses the same storage mechanism as uploads but with a longer TTL
// and a deterministic attachment ID (passed in rather than generated).

/**
 * Store base64 image data extracted from a session state payload.
 * The attachmentId is pre-generated by the caller (strip-images.ts).
 */
export async function storeExtractedImage(input: {
    attachmentId: string;
    sessionId: string;
    ownerUserId: string;
    mimeType: string;
    base64Data: string;
}): Promise<StoredAttachment> {
    const { attachmentId, sessionId, ownerUserId, mimeType, base64Data } = input;

    // Deduplicate: if this content-hashed ID already exists, just refresh its
    // expiry and return the existing record — no need to re-decode/write.
    const existing = attachments.get(attachmentId);
    if (existing) {
        const refreshedExpiry = Date.now() + EXTRACTED_IMAGE_TTL_MS;
        existing.expiresAt = new Date(refreshedExpiry).toISOString();
        existing.expiresAtMs = refreshedExpiry;
        void persistExtractedAttachment(existing).catch((err) => {
            console.error("[attachments] Failed to persist refreshed expiry:", err);
        });
        return existing;
    }

    // Strip data-URI prefix (e.g. "data:image/png;base64,") before decoding.
    // Upstream image payloads may arrive in data-URI form.
    const rawB64 = base64Data.includes(",") && base64Data.startsWith("data:")
        ? base64Data.slice(base64Data.indexOf(",") + 1)
        : base64Data;
    const bytes = Buffer.from(rawB64, "base64");
    const ext = mimeType.split("/").pop() ?? "png";
    const filename = `extracted-${attachmentId}.${ext}`;
    const targetPath = path.join(uploadRoot, filename);

    await mkdir(uploadRoot, { recursive: true });
    await Bun.write(targetPath, bytes);

    const createdAtMs = Date.now();
    const expiresAtMs = createdAtMs + EXTRACTED_IMAGE_TTL_MS;

    const record: StoredAttachment = {
        attachmentId,
        sessionId,
        ownerUserId,
        uploaderUserId: "system",
        filename,
        mimeType,
        size: bytes.length,
        createdAt: new Date(createdAtMs).toISOString(),
        expiresAt: new Date(expiresAtMs).toISOString(),
        expiresAtMs,
        filePath: targetPath,
    };

    attachments.set(attachmentId, record);
    void persistExtractedAttachment(record).catch((err) => {
        console.error("[attachments] Failed to persist extracted attachment:", err);
    });
    return record;
}

/**
 * Get the URL path for an extracted image attachment.
 * This is used by strip-images.ts to build the replacement URL.
 */
export function getExtractedImageUrl(attachmentId: string): string {
    return `/api/attachments/${attachmentId}`;
}

export async function sweepExpiredAttachments(nowMs: number = Date.now()): Promise<void> {
    const removals: Promise<void>[] = [];
    for (const [attachmentId, record] of attachments.entries()) {
        const expiresAtMs = record.expiresAtMs ?? Date.parse(record.expiresAt);
        if (!Number.isFinite(expiresAtMs) || expiresAtMs > nowMs) continue;
        removals.push(deleteStoredAttachment(attachmentId));
    }
    await Promise.all(removals);
}

// ── SQLite persistence for extracted images ──────────────────────────────────
// Extracted image metadata is persisted to SQLite so it survives server restarts.
// The in-memory Map remains the hot path; SQLite is written on store and read on boot.

export async function ensureExtractedAttachmentTable(): Promise<void> {
    await getKysely().schema
        .createTable("extracted_attachment")
        .ifNotExists()
        .addColumn("attachmentId", "text", (col) => col.primaryKey())
        .addColumn("sessionId", "text", (col) => col.notNull())
        .addColumn("ownerUserId", "text", (col) => col.notNull())
        .addColumn("filename", "text", (col) => col.notNull())
        .addColumn("mimeType", "text", (col) => col.notNull())
        .addColumn("size", "integer", (col) => col.notNull())
        .addColumn("createdAt", "text", (col) => col.notNull())
        .addColumn("expiresAt", "text", (col) => col.notNull())
        .addColumn("filePath", "text", (col) => col.notNull())
        .execute();
}

/** Persist an extracted attachment record to SQLite (upsert). */
async function persistExtractedAttachment(record: StoredAttachment): Promise<void> {
    await getKysely()
        .insertInto("extracted_attachment")
        .values({
            attachmentId: record.attachmentId,
            sessionId: record.sessionId,
            ownerUserId: record.ownerUserId,
            filename: record.filename,
            mimeType: record.mimeType,
            size: record.size,
            createdAt: record.createdAt,
            expiresAt: record.expiresAt,
            filePath: record.filePath,
        })
        .onConflict((oc) =>
            oc.column("attachmentId").doUpdateSet({
                expiresAt: record.expiresAt,
            }),
        )
        .execute();
}

/** Remove an extracted attachment record from SQLite. */
async function removePersistedAttachment(attachmentId: string): Promise<void> {
    await getKysely()
        .deleteFrom("extracted_attachment")
        .where("attachmentId", "=", attachmentId)
        .execute();
}

/**
 * Rehydrate the in-memory attachment registry from SQLite on server startup.
 * Only loads non-expired records whose files still exist on disk.
 */
export async function rehydrateExtractedAttachments(): Promise<number> {
    const nowMs = Date.now();
    const nowIso = new Date(nowMs).toISOString();

    // Delete expired rows first
    await getKysely()
        .deleteFrom("extracted_attachment")
        .where("expiresAt", "<=", nowIso)
        .execute();

    const rows = await getKysely()
        .selectFrom("extracted_attachment")
        .selectAll()
        .execute();

    let loaded = 0;
    for (const row of rows) {
        // Skip if file is missing from disk
        try {
            await access(row.filePath);
        } catch {
            await removePersistedAttachment(row.attachmentId);
            continue;
        }

        // Skip if already in memory (shouldn't happen on cold start, but be safe)
        if (attachments.has(row.attachmentId)) continue;

        const expiresAtMs = Date.parse(row.expiresAt);
        attachments.set(row.attachmentId, {
            attachmentId: row.attachmentId,
            sessionId: row.sessionId,
            ownerUserId: row.ownerUserId,
            uploaderUserId: "system",
            filename: row.filename,
            mimeType: row.mimeType,
            size: row.size as number,
            createdAt: row.createdAt,
            expiresAt: row.expiresAt,
            expiresAtMs,
            filePath: row.filePath,
        });
        loaded++;
    }

    return loaded;
}
