import { mkdir, rm } from "node:fs/promises";
import path from "node:path";

export interface StoredAttachment {
    attachmentId: string;
    sessionId: string;
    ownerUserId: string;
    uploaderUserId: string;
    filename: string;
    mimeType: string;
    size: number;
    createdAt: string;
    expiresAt: string;
    expiresAtMs?: number;
    filePath: string;
}

const DEFAULT_ATTACHMENT_TTL_MS = 15 * 60 * 1000;
const DEFAULT_MAX_FILE_SIZE_BYTES = 20 * 1024 * 1024;
/** Extracted images (from session state) persist for 24 hours. */
const EXTRACTED_IMAGE_TTL_MS = 24 * 60 * 60 * 1000;

function attachmentTtlMs(): number {
    const raw = Number.parseInt(process.env.PIZZAPI_ATTACHMENT_TTL_MS ?? "", 10);
    return Number.isFinite(raw) && raw > 0 ? raw : DEFAULT_ATTACHMENT_TTL_MS;
}

export function attachmentMaxFileSizeBytes(): number {
    const raw = Number.parseInt(process.env.PIZZAPI_ATTACHMENT_MAX_FILE_SIZE_BYTES ?? "", 10);
    return Number.isFinite(raw) && raw > 0 ? raw : DEFAULT_MAX_FILE_SIZE_BYTES;
}

const uploadRoot = path.resolve(process.env.PIZZAPI_ATTACHMENT_DIR ?? path.join(process.cwd(), ".pizzapi", "uploads"));

const attachments = new Map<string, StoredAttachment>();

export function sanitizeFilename(filename: string): string {
    return filename.replace(/[^a-zA-Z0-9._-]/g, "_");
}

export async function storeSessionAttachment(input: {
    sessionId: string;
    ownerUserId: string;
    uploaderUserId: string;
    file: File;
}): Promise<StoredAttachment> {
    const { sessionId, ownerUserId, uploaderUserId, file } = input;

    const attachmentId = crypto.randomUUID();
    const createdAtMs = Date.now();
    const expiresAtMs = createdAtMs + attachmentTtlMs();

    const safeName = sanitizeFilename(file.name || `attachment-${attachmentId}`);
    const targetPath = path.join(uploadRoot, `${attachmentId}-${safeName}`);

    await mkdir(uploadRoot, { recursive: true });
    const bytes = new Uint8Array(await file.arrayBuffer());
    await Bun.write(targetPath, bytes);

    const record: StoredAttachment = {
        attachmentId,
        sessionId,
        ownerUserId,
        uploaderUserId,
        filename: file.name || safeName,
        mimeType: file.type || "application/octet-stream",
        size: file.size,
        createdAt: new Date(createdAtMs).toISOString(),
        expiresAt: new Date(expiresAtMs).toISOString(),
        expiresAtMs,
        filePath: targetPath,
    };

    attachments.set(attachmentId, record);
    return record;
}

export function getStoredAttachment(attachmentId: string): StoredAttachment | null {
    const record = attachments.get(attachmentId);
    if (!record) return null;

    const expiresAtMs = record.expiresAtMs ?? Date.parse(record.expiresAt);
    if (expiresAtMs <= Date.now()) {
        void deleteStoredAttachment(attachmentId);
        return null;
    }

    return record;
}

export async function deleteStoredAttachment(attachmentId: string): Promise<void> {
    const record = attachments.get(attachmentId);
    if (!record) return;
    attachments.delete(attachmentId);
    try {
        await rm(record.filePath, { force: true });
    } catch {}
}

// ── Extracted image storage ──────────────────────────────────────────────────
// Used by strip-images.ts to offload inline base64 images from session state
// payloads. Uses the same storage mechanism as uploads but with a longer TTL
// and a deterministic attachment ID (passed in rather than generated).

/**
 * Store base64 image data extracted from a session state payload.
 * The attachmentId is pre-generated by the caller (strip-images.ts).
 */
export async function storeExtractedImage(input: {
    attachmentId: string;
    sessionId: string;
    ownerUserId: string;
    mimeType: string;
    base64Data: string;
}): Promise<StoredAttachment> {
    const { attachmentId, sessionId, ownerUserId, mimeType, base64Data } = input;

    // Decode base64 to raw bytes
    const bytes = Buffer.from(base64Data, "base64");
    const ext = mimeType.split("/").pop() ?? "png";
    const filename = `extracted-${attachmentId}.${ext}`;
    const targetPath = path.join(uploadRoot, filename);

    await mkdir(uploadRoot, { recursive: true });
    await Bun.write(targetPath, bytes);

    const createdAtMs = Date.now();
    const expiresAtMs = createdAtMs + EXTRACTED_IMAGE_TTL_MS;

    const record: StoredAttachment = {
        attachmentId,
        sessionId,
        ownerUserId,
        uploaderUserId: "system",
        filename,
        mimeType,
        size: bytes.length,
        createdAt: new Date(createdAtMs).toISOString(),
        expiresAt: new Date(expiresAtMs).toISOString(),
        expiresAtMs,
        filePath: targetPath,
    };

    attachments.set(attachmentId, record);
    return record;
}

/**
 * Get the URL path for an extracted image attachment.
 * This is used by strip-images.ts to build the replacement URL.
 */
export function getExtractedImageUrl(attachmentId: string): string {
    return `/api/attachments/${attachmentId}`;
}

export async function sweepExpiredAttachments(nowMs: number = Date.now()): Promise<void> {
    const removals: Promise<void>[] = [];
    for (const [attachmentId, record] of attachments.entries()) {
        const expiresAtMs = record.expiresAtMs ?? Date.parse(record.expiresAt);
        if (!Number.isFinite(expiresAtMs) || expiresAtMs > nowMs) continue;
        removals.push(deleteStoredAttachment(attachmentId));
    }
    await Promise.all(removals);
}
